version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: classconnect
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
