services:
  gateway:
    container_name: gateway
    build: .
    networks:
      - my-network
    ports:
      - 3000:3000
    env_file: .env
    environment:
      USERS_URL: http://users:3001
      EDUCATION_URL: http://education:3002
      ADMINS_URL: http://admins:3004
      JWT_SECRET: your_jwt_secret_here
      GATEWAY_TOKEN: gateway-token

networks:
  my-network:
    name: classconnect_net
